name       : fs-uae-launcher-dev
version    : 2.9.7
release    : 6
source     :
    - https://fs-uae.net/devel/2.9.7dev2/fs-uae-launcher-2.9.7dev2.tar.gz : a51fafef1ce8eac66a051402fb19ddcfba1935a1858d616bcc592264fa3deaa6
license    : GPL-2.0
component  : games.emulator
summary    : Frontend for FS-UAE Amiga Emulator (Development Version).
description: |
    An easy-to-use graphical configuration program which allows you to enjoy FS-UAE and Amiga emulation without writing configuration files.
builddeps  :
    - pkgconfig(python-3.5)
    - python3-qt5
rundeps    :
    - fs-uae-dev
    - python-lhafile
    - python-opengl
    - python3-qt5
setup      : |
    %patch -p1 < $pkgfiles/0001-launcher-Fallback-to-the-correct-path-within-Solus.patch
build      : |
    %python3_setup
install    : |
    python3 setup.py install --install-lib=%installroot%/usr/share/fs-uae-launcher --install-scripts=%installroot%/usr/bin
