name       : fs-uae-launcher-dev
version    : 3.0.5
release    : 11
source     :
    - https://fs-uae.net/stable/3.0.5/fs-uae-launcher-3.0.5.tar.gz : 27797a04b9fc0be2805ae992c2950ff6228383fa153eccefbdebfc6789ca76b6
license    : GPL-2.0-or-later
component  : games.emulator
homepage   : https://fs-uae.net/
summary    : Frontend for FS-UAE Amiga Emulator (Development Version)
description: |
    An easy-to-use graphical configuration program which allows you to enjoy FS-UAE and Amiga emulation without writing configuration files.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - fs-uae-dev
    - python-lhafile
    - python3-qt5
setup      : |
    %patch -p1 < $pkgfiles/0001-launcher-Fallback-to-the-correct-path-within-Solus.patch
build      : |
    %make
install    : |
    %make_install DESTDIR="$installdir" prefix=/usr
    rm -rf $installdir/usr/share/doc/
